[client]
# Показывать меню в боковой панели
showSidebarNavigation = true
initial_sidebar_state="auto"

[theme]
primaryColor="#6eb52f"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#e0e0ef"
textColor="#262730"
font="sans serif"
